name: Test
on: [push, pull_request] # usually you might prevent a change from being merged to main unless it passes tests
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout # checks out the branch
        uses: actions/checkout@v2 # find in docs for github actions

      - name: Install node
        uses: actions/setup-node@v2
        with: 
          node-version: 14

      - name: Install npm
        run: npm install -g npm@7

      - name: Install npm dependencies
        run: npm install

      - name: Run Jest
        run: npm test